<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Alxarafe.Modules.Catalog.Http</AssemblyName><RootNamespace>Alxarafe.Modules.Catalog.Http</RootNamespace></PropertyGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /><ProjectReference Include="../Alxarafe.Modules.Catalog.Application/Alxarafe.Modules.Catalog.Application.csproj" /><ProjectReference Include="../../../Alxarafe.AspNetCore/Alxarafe.AspNetCore.csproj" /><ProjectReference Include="../../../Alxarafe.Security/Alxarafe.Security.csproj" /></ItemGroup></Project>
