<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Alxarafe.Modules.Catalog.Module</AssemblyName><RootNamespace>Alxarafe.Modules.Catalog.Module</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="../Alxarafe.Modules.Catalog.Infrastructure/Alxarafe.Modules.Catalog.Infrastructure.csproj" /><ProjectReference Include="../Alxarafe.Modules.Catalog.Http/Alxarafe.Modules.Catalog.Http.csproj" /><ProjectReference Include="../../../Alxarafe.Modularity/Alxarafe.Modularity.csproj" /><ProjectReference Include="../../../Alxarafe.Security/Alxarafe.Security.csproj" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0"><PrivateAssets>all</PrivateAssets></PackageReference><PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" /><PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.18" /></ItemGroup></Project>
