<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Alxarafe.Modules.Catalog.Infrastructure</AssemblyName><RootNamespace>Alxarafe.Modules.Catalog.Infrastructure</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="../Alxarafe.Modules.Catalog.Application/Alxarafe.Modules.Catalog.Application.csproj" /><ProjectReference Include="../../../Alxarafe.EntityFrameworkCore/Alxarafe.EntityFrameworkCore.csproj" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0"><PrivateAssets>all</PrivateAssets></PackageReference><PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" /><PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.18" /></ItemGroup></Project>
