<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>Alxarafe.Security.EntityFrameworkCore</AssemblyName><RootNamespace>Alxarafe.Security.EntityFrameworkCore</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Alxarafe.Security/Alxarafe.Security.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>
</Project>
