<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Alxarafe.Modules.AiAgent.Application</AssemblyName>
        <RootNamespace>Alxarafe.Modules.AiAgent.Application</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Alxarafe.Modules.AiAgent.Domain/Alxarafe.Modules.AiAgent.Domain.csproj" />
    </ItemGroup>
</Project>
